---
title: "Prob Stats Homework 3"
output: html_notebook
---
## Author
Tantatorn Suksangwarn 61010402 

## Problem
Example 7.14 Assume that in a digital communication channel, the number of bits received in error can be modeled
by a binomial random variable, and assume that the probability that a bit is received in error is
1 × 10 − 5 . If 16 million bits are transmitted, what is the probability that 150 or fewer errors occur?
Let the random variable X denote the number of errors. Then X is a binomial random variable and
$$
\begin{equation*}
P(X\leq150)   = \sum_{x=0}^{150}{16000000 \choose x} (10^{-5})^x (1-10^{-5})^{ 16000000-x}
\end{equation*}
$$
Practical Interpretation: Clearly, this probability is difficult to compute. Fortunately, the normal distribution can be
used to provide an excellent approximation in this example.
## Solution

### Way I
Calculate the probability by using loop
dbinom is R builtin function for compute binomial distribution
```{r}
binomial_result <- 0
p <- 0.00001

for (i in 0:150){
   binomial_result <- binomial_result + dbinom(i,size = 16000000,p)
}
print(binomial_result)
```
### Way II
Calculate by using Normal Approximation
Find the Z-Score of X=0 and X=150
$$
\begin{equation*}
Z   = {{X-np} \over {\sqrt{np(1-p)}}}
\end{equation*}
$$
```{R}
avg = 16000000*p
z_score_a <- -avg/(sqrt(avg*(1-p)))
z_score_b <- (150-avg)/(sqrt(avg*(1-p)))
print(z_score_a)
print(z_score_b)
```
Let's use normal approximation
$$
\begin{equation*}
P(X\le150)   = \phi(-0.7906) - \phi(-12.6492)
\end{equation*}
$$
pnorm is R builtin function for compute normal distribution
```{R}
norm_result <- pnorm(c(z_score_b))-pnorm(c(z_score_a))
print(norm_result)
```
## Comparison
Let's compare both results
```{R}
result <- c(binomial_result,norm_result)
names(result) <- c("Binomial distribution","Normal approximation")
print(result)
```
At last, let's draw some graph to compare both
First, Let's try binomial distribution
```{R}
x <- dbinom(0:150,size=16000000,prob=p)
barplot(x,names.arg=0:150,main="Binomial distribution")
```
Last, Let's try out normal distribution
```{R}
x=seq(0,300,length=100)
y=dnorm(x,mean=avg,sd=avg*(1-p))
plot(x,y,type="l",lwd=2,col="red",main="Normal approximation")
x=seq(0,150,length=100)
y=dnorm(x,mean=avg,sd=avg*(1-p))
polygon(c(0,x,150),c(0,y,0),col="gray")
```